### ISSUE TITLE
521 at API Server

### ISSUE THREAD

**Issue by Aldiwildan77** [Psystec/RUST-Update-Notice#1]
Hi, I'm using your plugin for my rust server, but when I try to install it an error occurs as 521 Cloudflare error, I think the webserver is down. Please help to resolve this, or should I change the API server URL?

![image](https://user-images.githubusercontent.com/29916319/124687211-ac608c00-defe-11eb-97a1-1a2697bec004.png)

**Comment by Psystec** [comment]
Hi, thank you for contacting me. I am aware of this issue. If you need more
information please join the discord: https://discord.gg/EyRgFdA

Regards
Psystec
